def on_on_chat():
    agent.move(UP, 1)
    for index in range(3):
        agent.move(FORWARD, 1)
        agent.set_slot(1)
        agent.place(DOWN)
        agent.move(FORWARD, 1)
        agent.set_slot(2)
        agent.place(DOWN)
        agent.move(FORWARD, 1)
        agent.set_slot(3)
        agent.place(DOWN)
    agent.move(BACK, 9)
    agent.set_slot(4)
    agent.place(DOWN)
player.on_chat("4", on_on_chat)
