name: 教案問題回報
description: 回報半日營教案問題
title: "[教案問題] "

body:
  - type: markdown
    attributes:
      value: |
        提交前，可以先查看是否已有相同問題：
        [查看大家回報的問題](https://github.com/seanhuang9527/minecraft-half-day-camp/issues)

  - type: dropdown
    id: lesson
    attributes:
      label: 選擇梯次
      options:
        - 梯次 A｜迴圈：求生大冒險
        - 梯次 B｜迴圈：紅石工程師
        - 梯次 C｜巢狀迴圈：怪物攻城戰
        - 梯次 D｜巢狀迴圈：礦坑達人
        - 梯次 E｜巢狀迴圈：沙漠荒野
        - 梯次 F｜條件判斷：紅石樂園
        - 梯次 G｜迴圈與方向：怪物專家
        - 梯次 H｜巢狀迴圈：新夢幻農場
        - 梯次 I｜變數：狩獵大師
        - 梯次 J｜巢狀迴圈：程式造橋闖關
        - 梯次 K｜變數：挖礦挑戰賽
        - 梯次 L｜條件判斷：方塊崩落大逃亡
        - 梯次 M｜隨機數：閃動格子
        - 神木村
        - 半日營 SOP
        - 其他
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 遇到什麼問題？
      placeholder: 請簡單說明問題，也可以直接拖入截圖。
    validations:
      required: true
